from __future__ import annotations

TEXT_PLAIN_MEDIA_MODE = "text/plain"
APPLICATION_JSON_MEDIA_MODE = "application/json"
IMAGE_ANY_MEDIA_MODE = "image/*"

DEFAULT_INPUT_MEDIA_MODES = [
    TEXT_PLAIN_MEDIA_MODE,
    IMAGE_ANY_MEDIA_MODE,
    APPLICATION_JSON_MEDIA_MODE,
]
DEFAULT_OUTPUT_MEDIA_MODES = [
    TEXT_PLAIN_MEDIA_MODE,
    APPLICATION_JSON_MEDIA_MODE,
]
JSON_OUTPUT_MEDIA_MODES = [APPLICATION_JSON_MEDIA_MODE]
TEXT_OUTPUT_MEDIA_MODES = [TEXT_PLAIN_MEDIA_MODE]
JSON_RPC_INPUT_MEDIA_MODES = [APPLICATION_JSON_MEDIA_MODE]
